[package]
name = "embedded"
version = "0.1.0"
authors = ["Pierre-Emile Ferron <peferron@gmail.com>"]

[dependencies]
redis = "0.8.0"
serial = "0.3"

[[bin]]
name = "reader"
path = "src/reader.rs"

[[bin]]
name = "pusher"
path = "src/pusher.rs"

[lib]
name = "common"
path = "src/common.rs"
