[package]
name = "embedded-uploader"
version = "0.1.0"
authors = ["Pierre-Emile Ferron <peferron@gmail.com>"]

[dependencies]
hyper = "0.10"
redis = "0.8.0"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
