[package]
name = "api-server"
version = "0.1.0"
authors = ["Pierre-Emile Ferron <peferron@gmail.com>"]

[dependencies]
chrono = { version = "0.3", features = ["serde"] }
hyper = "0.10"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
